export default {
  "login": "Cryptim",
  "id": 67354557,
  "node_id": "MDQ6VXNlcjY3MzU0NTU3",
  "avatar_url": "https://avatars.githubusercontent.com/u/67354557?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Cryptim",
  "html_url": "https://github.com/Cryptim",
  "followers_url": "https://api.github.com/users/Cryptim/followers",
  "following_url": "https://api.github.com/users/Cryptim/following{/other_user}",
  "gists_url": "https://api.github.com/users/Cryptim/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Cryptim/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Cryptim/subscriptions",
  "organizations_url": "https://api.github.com/users/Cryptim/orgs",
  "repos_url": "https://api.github.com/users/Cryptim/repos",
  "events_url": "https://api.github.com/users/Cryptim/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Cryptim/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Timothy Ignatius Agbor",
  "company": "@africad and afritech ",
  "blog": "www.linkedin.com/in/timothy-ignatius-24a361210",
  "location": "Lagos",
  "email": null,
  "hireable": null,
  "bio": "Hello there! I'm Timothy, a passionate web developer with a knack for building  beautiful and intuitive web applications.",
  "twitter_username": null,
  "public_repos": 14,
  "public_gists": 0,
  "followers": 1,
  "following": 10,
  "created_at": "2020-06-24T03:16:51Z",
  "updated_at": "2023-07-03T05:57:41Z"
};
